default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.database_username %>
  timeout: 5000
  encoding: unicode
  database: <%= Rails.application.credentials.database_name %>
  password: <%= Rails.application.credentials.database_password %>

development:
  <<: *default

production:
  <<: *default

# test:
#   <<: *default
#   database: myndheal_test
#   password: password1
